package Tims.Partial_Report_SOFT_1409_Test_Cases;

import java.io.IOException;

import org.testng.annotations.Test;

import Test.Tims.Partial_Report_Action_Class.SOFT_1409_Partial_Report_Actions;
import initializer.BaseClass;

public class TC_01_Verify_Partial_Test_Reporting_For_The_General_Health_Test_Specifically_For_The_Biomarkers_HbA1c_with_Error_Reason_Marked_As_Untestable_Grossly_Haemolysed extends BaseClass {

	SOFT_1409_Partial_Report_Actions soft_1409_partial_report_actions;
	
	@Test
	public void TC_01_Verify_partial_test_reporting_for_the_general_health_test_specifically_for_the_biomarkers_HbA1c_with_error_reason_marked_as_untestable_grossly_haemolysed() throws InterruptedException, IOException {
		soft_1409_partial_report_actions = new SOFT_1409_Partial_Report_Actions(getDriver());
		soft_1409_partial_report_actions.partialReportTC1();
		
	}
}
